version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 7010:8010
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: world
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234

